version: "3.8"

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - ./data:/app/data

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: dashboard
    network_mode: "service:api"
    environment:
      - API_URL=http://localhost:8000
    depends_on:
      - api
